clusters:
- name: minikube
  destinationServer: https://kubernetes.default.svc
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"

    sampleApp:
      enabled: true
      branch: HEAD

#- name: gke
#  destinationServer: #INSERT MASTERIP HERE
#  apps:
#    prometheus:
#      enabled: true
#      version: "9.7.4"
#    sampleApp:
#      enabled: true
#      branch: HEAD