apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: nginx
spec:
  replicas: {{ .Values.nginx.replicas}}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image }}:{{ .Values.nginx.tag }}"
        ports:
        - containerPort: 80